version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./microservicos:/projeto_final/microservicos
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kay30lane090
      POSTGRES_DB: compra_passagens
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
